module.exports = [
    {
        name: "Los Angeles Marathon",
        description: "Join us for the 38th running of the Los Angeles Marathon  presented by ASICS on March 19, 2023. Participants will set out on our course starting at Dodger Stadium and finishing on the Avenue of the Stars in Century City and not only accomplish a personal goal but also support The McCourt Foundation's mission to build a healthier world. Join us!",
        location: "Los Angeles, CA",
        date: "March 19, 2023",
        image: "https://images.rove.me/w_1920,q_85/o5ymbowymy39hbdrgy9n/los-angeles-los-angeles-marathon.jpg",
        source: "https://www.lamarathon.com/pages/la-marathon",
        signup: "https://endurancecui.active.com/new/events/81075432/select-race?error=login_required&state=eb8c8dd2-822c-4365-a09b-662d4e46a267&_p=4936230039661593",    
        price: "169.00",
        latlng: [34.074019830917145, -118.23988319943354],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Orange County Marathon",
        description: "The OC Marathon promotes an active and healthy lifestyle and seeks to inspire kids to fitness. The 5k happens on Saturday with the half and full marathon events running on Sunday. Both Sunday races start in Newport Beach and finish in Costa Mesa, followed by the Ultimate Finish Line Festival. There are a few hills along the way, but both courses are net downhill. The event encourages community and business involvement to positively affect the lives of our runners and families while supporting charities.",
        location: "Orange County, CA",
        date: "May 1, 2022",
        image: "https://www.newportbeachvacationproperties.com/uploads/World-class-OC-Marathon-half-marathon-starting-line.jpg",
        source: "https://ocmarathon.com/",
        signup: "https://wdc.rccal.com/racecentralpublic/main.cfm/ocmarathon2022/BA9A56CE0A9BFA26E8ED9E10B2CC8F46/?do=userform&f=1",    
        price: "145.00",
        latlng: [33.616392209118345, -117.88166234875722],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Long Beach Marathon",
        description: "Experience one of the most scenic events in California, “Run Long Beach”. Starting in Downtown Long Beach, runners head towards the historic Queen Mary and then through Shoreline Village. After running next to the Pacific Ocean on the flat beach path, half marathoners will continue down Ocean Boulevard while full marathoners veer right and head through Belmont Shore toward Marine Stadium.The Long Beach Marathon offers two days of events for everyone including a Marathon, Half Marathon, 20-mile Bike Tour (untimed), the Aquarium of the Pacific 5K (which runs THROUGH the aquarium), and a Kids Fun Run. All registered participants receive shirts, medals, and bibs.",
        location: "Long Beach, CA",
        date: "October 9, 2022",
        image: "https://d178fu9mi2dmkb.cloudfront.net/uploads/2018/02/27065402/JetBlue-Long-Beach-Marathon-1024x636.jpg",
        source: "https://www.runlongbeach.com/",
        signup: "https://endurancecui.active.com/new/events/76376032/select-race?error=login_required&state=7eaca70f-b6c2-4e4c-ada0-b019e7ebeda1&_p=6172847620703998",    
        price: "129.00",
        latlng: [33.76322418344942, -118.19814027245643],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Rock 'n' Roll San Diego",
        description: "This is the Original Rock 'n' Roll! Bringing the fun to the run since 1998, Rock 'n' Roll San Diego is a favorite among locals and tourists alike. Starting at Balboa Park and finishing in Downtown San Diego, you’ll explore up to eight well-known neighborhoods and experience an insider tour that even the locals rave about. This ultimate foot tour highlights all the iconic communities, their personalities, and everything we love about America's Finest City: San Diego, CA.",
        location: "San Diego, CA",
        date: "June 5, 2022",
        image: "https://wmimg.azureedge.net/public/img/marathons/rock-n-roll-san-diego-marathon/bDMIHX_rock-n-roll-san-diego-marathon.jpg?c=1504021541",
        source: "https://www.runrocknroll.com/san-diego",
        signup: "https://endurancecui.active.com/new/events/78852131/select-race?error=login_required&state=656a2ed4-ad2f-4f37-b239-7702406a19d0&_p=6678980437470509",    
        price: "129.00",
        latlng: [32.73681829998196, -117.15946534549002],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Carlsbad Marathon & Half",
        description: "The BEST and most scenic winter race with the BEST swag! Miles and miles of breathtaking ocean views with outstanding course support and entertainment. Turn your Martin Luther King Jr. holiday weekend into a run-cation! Register now!",
        location: "Carlsbad, CA",
        date: "January 15, 2023",
        image: "https://inmotionevents.com/wp-content/uploads/2020/01/2020CarlsbadMarathonbyCruse0325_web.jpg",
        source: "https://inmotionevents.com/event/carlsbad-marathon/",
        signup: "https://events.com/r/en_US/registration/2023-carlsbad-marathon-half-marathon-double-down--5k-carlsbad-january-826279",    
        price: "119.00",
        latlng: [33.17075030082306, -117.34855187581299],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Santa Clarita Marathon",
        description: "The Santa Clarita Marathon, which is an official qualifying race for the Boston Marathon, will test the physical boundaries of the human body. The weekend will include a Full Marathon, Half Marathon, 10K run, 5K run and Mayor’s Walk. Want more of a challenge? Sign up for two or more races on the Marathon weekend.  Runners who register for the 5 and 10K Double Feature should be able to finish the 10K in under 1 hour.  The 5K start line will remain open until 8:10 to accommodate 10K runners. Runners will receive a special medal for completing their challenge.",
        location: "Santa Clarita, CA",
        date: "February 12, 2023",
        image: "https://scvnews.com/wp-content/uploads/2019/11/signal-marathon-1-carlos-larios-winner-gilbert-bernal-20191103.jpg",
        source: "https://scmarathon.org/",
        signup: "https://endurancecui.active.com/new/error?error=login_required&state=734dbbda-2feb-45e3-8c3d-ae8b59f89f36&_p=5198084639339658",    
        price: "129.00",
        latlng: [34.41579518574718, -118.55728115882579],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Camarillo Marathon",
        description: "Experience an all-flat course along the Camarillo bike path with no road traffic to worry about! This marathon course is 4-loops and is also a Boston Qualifier.",
        location: "Camarillo, CA",
        date: "August 7, 2022",
        image: "https://wmimg.azureedge.net/public/img/marathons/camarillo-marathon/camarillo-marathon.jpg",
        source: "https://camarillomarathon.com/",
        signup: "https://www.letsdothis.com/us/e/camarillo-marathon-half-marathon-10k-5k-71063",    
        price: "140.00",
        latlng: [34.21501099816123, -119.02703013491711],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Ventura Marathon",
        description: "The LaceUp Running Series Ventura Marathon is an exceptional race and finish experience for runners and their friends. This premier running race is followed by a local food truck brunch and a craft beer finish line toast in a lively event hub. Share your success or follow friends using LaceUp’s realtime results and photos.The chip-timed Ventura Marathon is a Boston qualifier race and can opt for the Half Marathon, 10k and 5k distances.",
        location: "Ventura, CA",
        date: "February 27, 2022",
        image: "https://venturamarathon.com/images/LU19_Ventura_SeanRyan-2473-1-1024x683.jpg",
        source: "http://venturamarathon.com/",
        signup: "https://runsignup.com/Race/CA/Ventura/VenturaMarathon",    
        price: "129.00",
        latlng: [34.4514847277444, -119.19731500194324],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Mountains 2 Beach Marathon & Half",
        description: "Run a course surrounded by the beautiful Ojai mountains that will have you winding through the Ventura River Valley to the pristine beaches of the last great surf town, Ventura California. This point to point race winds through the Ventura River Valley as it makes its way to the pristine beaches of the last great surf town in California, Ventura. Runners love gradual downhill nature and amazing weather, which is prime to make you faster, but not hurt the knees. After a pancake flat tour of beach front Ventura, runners and their families are treated to a finish line party only steps away from the surf and the shops and restaurants of Historic Downtown Ventura.",
        location: "Ojai, CA",
        date: "June 5th, 2022",
        image: "https://mountains2beachmarathon.com/wp-content/uploads/2019/06/Full-Start-Line-1024x576.jpg",
        source: "https://mountains2beachmarathon.com/",
        signup: "https://runsignup.com/Race/Register/?raceId=4487",    
        price: "159.00",
        latlng: [34.44791522704086, -119.24323095683108],
        tags: ["Full","Half","5k"]
    },
    {
        name: "REVEL Big Bear Marathon & Half Marathon",
        description: "This incredibly fast and remarkably beautiful road race takes runners from the majestic mountains and pristine forests of Big Bear to the foothills of Redlands, California. Featuring a smooth downhill slope and spectacular scenery in the San Bernardino National Forest, this race will be sure to help you set your PR and finally hit that Boston Qualifying time. REVEL Big Bear is the fastest and most beautiful marathon and half marathon in California! REVEL in speed. REVEL in beauty. REVEL in Big Bear.",
        location: "Redlands, CA",
        date: "November 12, 2022 ",
        image: "https://brookseeevents.s3.amazonaws.com/rev/2016/albums/REV-16_newsletter_feb_feature%20image_2.jpg",
        source: "https://www.runrevel.com/rbb",
        signup: "https://www.runrevel.com/rbb/register",    
        price: "119.99",
        latlng: [34.17382974418123, -116.8553691871909],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Surf City Marathon & Half Marathon",
        description: "This award-winning course is considered one of the best courses in the country and is well known for being scenic and flat. The race starts along the Pacific Coast Highway and passes by the famous Huntington Beach pier where runners will enjoy the beauty of the Bolsa Chica Wetlands as you start your turn. All participants finish down the Pacific Coast Highway and kick it up a notch for the crowds at Main Street on their way to a monumental finish line moment and continue their celebrations at the “Sand Bar” right on the beach!",
        location: "Huntington Beach, CA",
        date: "February 5,2023",
        image: "https://www.ocregister.com/wp-content/uploads/2019/02/OCR-L-SURFCITYMARATHON-0204.021.jpg",
        source: "https://www.runsurfcity.com/",
        signup: "https://endurancecui.active.com/new/events/80512134/select-race?error=login_required&state=758bf2bb-ffd0-4739-8387-1a5c073d7029&_p=5227571909992191",    
        price: "99.00",
        latlng: [33.65532237770226, -118.00405117318637],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Griffith Park Trail Marathon Relay & 8K",
        description: "One of the largest urban parks in the country, Griffith Park is a 4,300-plus acre slice of runner heaven. The grounds include famous sites like the Abandoned Los Angeles Zoo, the Observatory, and the Hollywood Sign, with more than 30 trails totaling around 50 miles for runners and hikers. Join the Griffith Park Trail Relay Marathon, get ready to run 5.25 miles individually, and get a taste of what the second-largest city park has to offer.",
        location: "Los Angeles, CA",
        date: "June 5, 2022",
        image: "https://griffithparkmarathonrelay.com/wp-content/uploads/2017/10/gptmr15-6603.jpg",
        source: "https://griffithparkmarathonrelay.com/",
        signup: "https://runsignup.com/Race/CA/LosAngeles/GriffithParkTrailMarathonRelay8K",    
        price: "289.00",
        latlng: [34.13288541365393, -118.28095730692849],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Catalina Island Marathon",
        description: "This 'bucket list' marathon features the exciting and historic marathon course used for decades on the Catalina Island Conservancy’s lands. This includes much of the rugged terrain, spectacular vistas, challenging climbs and special challenges enjoyed by thousands of runners over the years!",
        location: "Avalon, CA",
        date: "March 11, 2023",
        image: "https://mybestruns.com/photo/2927.jpg?ver=1518630891",
        source: "https://www.catalinaislandmarathon.com/",
        signup: "https://www.catalinaislandmarathon.com/Race/Register/?raceId=73049",    
        price: "150.00",
        latlng: [33.44067960266768, -118.4984587785518],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Seaside Marathon",
        description: "Miles of Ocean views that will keep you in awe as you stroll along the Ventura beachfront. Mostly flat, two loop Full marathon course. Half Marathon, 5k and 10k distances available too. Certified Boston Qualifier Course ",
        location: "Ventura, CA",
        date: "February 20, 2022",
        image: "https://www.ocregister.com/wp-content/uploads/2019/02/OCR-L-SURFCITYMARATHON-0204.041.jpg",
        source: "https://seasidemarathon.com/",
        signup: "https://secure.elitesportsca.com/event/seaside-marathon-ca-2022",    
        price: "95.99",
        latlng: [34.293462288938535, -119.33903739733483],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Two Cities Marathon",
        description: "The Two Cities Marathon starts and finishes at the beautiful Clovis Community College. This Boston qualifying marathon course was redesigned in 2021 to offer a scenic and truly flat course. Just 60 miles from Yosemite, Kings Canyon, and Sequoia National Parks, home of the largest and oldest redwoods in the World! With plenty of hotels to choose from, you can see why many participants run, stay, and play!",
        location: "Fresno, CA",
        date: "November 6, 2022",
        image: "https://ftw.usatoday.com/wp-content/uploads/sites/90/2016/11/usp_running__new_york_marathon_77206180.jpg?w=1000&h=600&crop=1",
        source: "https://runsignup.com/Race/CA/Fresno/TwoCitiesMarathonandHalf",
        signup: "https://runsignup.com/Race/Register/?raceId=27723&eventId=567213",    
        price: "95.00",
        latlng: [36.88118866150618, -119.7475680577764],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Golden Gate Headlands Marathon",
        description: "As you reach the summits of this course, you'll take in a view of San Francisco Bay tucked behind the rolling green hills of the Marin Headlands to the east and looking west you will view the Pacific Ocean. One thing's certain...the views this course offers are unlike any other.",
        location: "Tulare County, CA",
        date: "March 26, 2023",
        image: "https://res.cloudinary.com/letsdothiscom/image/upload/a_auto,dpr_auto,f_auto,h_630,q_auto,w_1200/v1611237678/event-assets/kbkzdbs3sd0u24xpdv2h.jpg",
        source: "https://raceroster.com/events/2022/48081/2022-golden-gate-headlands-marathon-half-marathon-and-10k?aff=FZ4HS",
        signup: "https://raceroster.com/events/2022/48081/2022-golden-gate-headlands-marathon-half-marathon-and-10k?aff=FZ4HS",    
        price: "120.00",
        latlng: [37.85106380452995, -122.51904815508124],
        tags: ["Full","Half","5k"]
    },
    {
        name: "San Lorenzo River Trail Run",
        description: "Run through 300 foot tall, 1500 year-old Coastal Redwoods, lush stream canyons, open meadows, pine and oak forests, and high dry chaparral-covered ridges. Choose from your choice of race distances 10k, half marathon, 30k, marathon or 50k - there's something for everyone!",
        location: "Santa Cruz, CA",
        date: "April, 24, 2022",
        image: "https://res.cloudinary.com/letsdothiscom/image/upload/a_auto,dpr_auto,f_auto,h_630,q_auto,w_1200/v1611237678/event-assets/qsz4xah4nfepet7efx1z.jpg",
        source: "http://www.coastaltrailruns.com/slr_san_lorenzo_river.html",
        signup: "https://runsignup.com/Race/CA/SantaCruz/SanLorenzoRiverTrailRun",    
        price: "70.00",
        latlng: [36.983680563663206, -122.03809591359374],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Lake Chabot Trail Challenge",
        description: "The half marathon course is a scenic, hilly loop, mainly on dirt fire roads.  The ridge-line views look down upon scenic Lake Chabot, surrounding grassy slopes, and eucalyptus groves.  Mt. Diablo and San Francisco Bay are visible along the route. There are water stations with first aid and radio support.",
        location: "Castro Valley, CA",
        date: "June 5, 2022",
        image: "https://res.cloudinary.com/letsdothiscom/image/upload/a_auto,dpr_auto,f_auto,h_630,q_auto,w_1200/v1611237678/event-assets/eq1uti4qbfxzzzumvqcc.jpg",
        source: "https://runsignup.com/Race/CA/CastroValley/LakeChabotTrailChallenge?aflt_token=EZnEDCiIAbEP0IXNk3reBNJGJev1hmeL",
        signup: "https://runsignup.com/Race/Register/?raceId=21928&eventId=555254",    
        price: "55.00",
        latlng: [37.71553113574117, -122.10251356198678],
        tags: ["Full","Half","5k"]
    },
    {
        name: "San Francisco Marathon",
        description: "Welcome to Speed City, USA! Nicknamed after the legendary San Jose State track teams of the 60s, San Jose is all about speed. United Airlines Rock ‘n’ Roll San Jose is no different. Run at PR-setting speed on a course that’s bursting with San Jose spirit and loved by the world’s best elites. Live-bands, DJs, cheer squads and fans jam the streets of downtown San Jose from start to finish, making this one of the most spirited running block parties you can find!",
        date: "october 9, 2022",
        image: "http://nk52l3tul6x3a6ogk25ywu4j.wpengine.netdna-cdn.com/wp-content/uploads/2015/05/TSFM_2015_MBP_JPG-90DPI-59-1024x683.jpg",
        source: "https://www.runrocknroll.com/san-jose",
        signup: "https://endurancecui.active.com/new/events/78132533/select-race?error=login_required&state=c6ad97ed-a086-42c5-a1b8-ccbcf1cc28c3&_p=26292853548180284",    
        price: "99.00",
        latlng: [37.79031288981025, -122.38915662219766],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Santa Rosa Marathon",
        description: "The Santa Rosa Marathon returns August 27-28, 2022, for another spectacular weekend running through the heart of California wine country. Treat yourself to scenic miles through dazzling vineyards and scenic pastoral beauty along mostly flat courses in beautiful Sonoma County. Whether you run the 5K, 10K, half marathon, or marathon, we’ll be joining you at the finish for an after-party with a complementary beer (if 21+) at Old Courthouse Square in downtown Santa Rosa. Plus, all marathon and half marathon finishers will take home a bottle of wine from Deloach Vineyards. ",
        location: "Santa Rosa, CA",
        date: "August 28, 2022",
        image: "https://imengine.prod.srp.navigacloud.com/?uuid=9951CD40-FFB5-4C2D-AE16-B268BD6A267F&type=primary&q=72&width=1024",
        source: "https://santarosamarathon.com/",
        signup: "https://venturesendurance.enmotive.com/events/register/2022-santa-rosa-marathon",    
        price: "180.00",
        latlng: [38.4364370166969, -122.71350628657869],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Rock n Roll San Jose",
        description: "The Santa Rosa Marathon returns August 27-28, 2022, for another spectacular weekend running through the heart of California wine country. Treat yourself to scenic miles through dazzling vineyards and scenic pastoral beauty along mostly flat courses in beautiful Sonoma County. Whether you run the 5K, 10K, half marathon, or marathon, we’ll be joining you at the finish for an after-party with a complementary beer (if 21+) at Old Courthouse Square in downtown Santa Rosa. Plus, all marathon and half marathon finishers will take home a bottle of wine from Deloach Vineyards. ",
        location: "Santa Rosa, CA",
        date: "August 28, 2022",
        image: "https://imengine.prod.srp.navigacloud.com/?uuid=9951CD40-FFB5-4C2D-AE16-B268BD6A267F&type=primary&q=72&width=1024",
        source: "https://santarosamarathon.com/",
        signup: "https://venturesendurance.enmotive.com/events/register/2022-santa-rosa-marathon",    
        price: "180.00",
        latlng: [37.33299864123373, -121.88543318607992],
        tags: ["Full","Half","5k"]
    },
    {
        name: "Rock n Roll San Jose",
        description: "The Santa Rosa Marathon returns August 27-28, 2022, for another spectacular weekend running through the heart of California wine country. Treat yourself to scenic miles through dazzling vineyards and scenic pastoral beauty along mostly flat courses in beautiful Sonoma County. Whether you run the 5K, 10K, half marathon, or marathon, we’ll be joining you at the finish for an after-party with a complementary beer (if 21+) at Old Courthouse Square in downtown Santa Rosa. Plus, all marathon and half marathon finishers will take home a bottle of wine from Deloach Vineyards. ",
        location: "Santa Rosa, CA",
        date: "August 28, 2022",
        image: "https://imengine.prod.srp.navigacloud.com/?uuid=9951CD40-FFB5-4C2D-AE16-B268BD6A267F&type=primary&q=72&width=1024",
        source: "https://santarosamarathon.com/",
        signup: "https://venturesendurance.enmotive.com/events/register/2022-santa-rosa-marathon",    
        price: "180.00",
        latlng: [37.33299864123373, -121.88543318607992],
        tags: ["Full","Half","5k"]
    },
    

    

]